Fix type error about HTTP headers
Fixes this type checking error:

```
TypeCheckError: Type 'RequestHeaders' is not assignable to type 'Record<string, string | Uint8Array<ArrayBufferLike>>'.
  Index signature for type 'string' is missing in type 'RequestHeaders'.
 ❯ src/lib/services/HttpProxy/HttpProxy.ts:118:8
```